export const products = [
  {
    id: 1,
    name: "Slim Fit Cotton T-Shirt",
    price: 999,
    inStock: true,
    rating: 4.3,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRLbrkhtI_QCKgZtTqWOBqe5p9bR5fvBaMIo0sF0z0j9BGQ0MRlUPTsezE4Gqfggfekp6uPhLp9S-72O3pVNjhwpmaiaovgWqALqIMzzZzgLQu2o_YoBSf-7w&usqp=CAE",
    category: "T-Shirt",
    size: ["S", "M", "L", "XL"],
    material: "100% Cotton",
  },
  {
    id: 2,
    name: "Denim Jacket",
    price: 2499,
    inStock: true,
    rating: 4.8,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzHHmG_O-WiVWqmzcXlNf1KsQIEVfxMxX4AewXxmgO9nRElQVdJ9porkbhqjNu2dsN0oKgwgw5KHrm8kXeLKQy-D5PAEGKkfbbnFzCTpWqwxCW4d8QGFCu&usqp=CAE",
    category: "Jacket",
    size: ["M", "L", "XL"],
    material: "Denim",
  },
  {
    id: 3,
    name: "Leather Chelsea Boots",
    price: 3999,
    inStock: false,
    rating: 4.7,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzOj-u6vEzwKAQ6JjaSPtT6B_jwhfmdxUFi6pDIQYAQPVTfkuqS-SDKfcZKbpGFSVbSWkvuWEPuwSONvd4MBYnN2HqOxr6WxRWII-jrAEpB3UP7rnqmLW8&usqp=CAE",
    category: "Footwear",
    size: ["8", "9", "10", "11"],
    material: "Leather",
  },
  {
    id: 4,
    name: "Skinny Fit Jeans",
    price: 1999,
    inStock: true,
    rating: 3.5,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSkLyPkha1AEF5nGFHD_wGEtR9hqLMrZY3yt_QB3a9y3-Gwtfu8wESw_vdDDe-El3_AG-CJIxfoSXr86cAgvHiLN2BWNnhzYdym-FYBuaVUzQPCBE7RogM6Tw&usqp=CAE",
    category: "Jeans",
    size: ["28", "30", "32", "34", "36"],
    material: "Stretch Denim",
  },
  {
    id: 5,
    name: "Oversized Hoodie",
    price: 1499,
    inStock: true,
    rating: 3.6,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSfKB5RUVnV8mDLHP688vr4eZKASNkked9lMUmTWYYTJ91SxWOwYyHwSD6UGZTEBOdnR7VsHuv30VPIGRyXPmK1_ogb1KYwh5RJFoi3oWQtYG0OsUK8R4gfsw&usqp=CAE",
    category: "Hoodie",
    size: ["S", "M", "L", "XL"],
    material: "Fleece Cotton",
  },
  {
    id: 6,
    name: "Classic Sneakers",
    price: 2999,
    inStock: false,
    rating: 3.2,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR2zpoaKr8GRRMBlJT-zIOyV-MUWsbnYWTgrWGkQurPmjrSh6KDFkEOx72ebfuqc3EX5YmRkeqOdHIKBrQSed04LgYhsX78y4Pm8QTR0qL9tU4hP5jmTKAQ&usqp=CAE",
    category: "Footwear",
    size: ["8", "9", "10", "11"],
    material: "Canvas",
  },
];
